#配置中文编码格式
server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #端口号
  port: 8080

spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias_db
    username: root
    password: 123456
  servlet:
    #配置单个文件最大上传大小
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#自定义的阿里云OSS配置信息
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: cloud-tlias